# SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v0.1.0)"
        required: true
      message:
        description: "Tag message"
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create Tag
        uses: negz/create-tag@39bae1e0932567a58c20dea5a1a0d18358503320 # v1
        with:
          version: ${{ github.event.inputs.version }}
          message: ${{ github.event.inputs.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
